export default [
  {
    pin: 101,
    name: 'Agnieszka',
    surname: 'Wojtyła',
    isWorking: false,
  },
  {
    pin: 101,
    name: 'Agnieszka',
    surname: 'Wojtyła',
    isWorking: false,
  },
  {
    pin: 101,
    name: 'Agnieszka',
    surname: 'Wojtyła',
    isWorking: false,
  },
  {
    pin: 101,
    name: 'Agnieszka',
    surname: 'Wojtyła',
    isWorking: false,
  },
  {
    pin: 101,
    name: 'Agnieszka',
    surname: 'Wojtyła',
    isWorking: false,
  },
  {
    pin: 101,
    name: 'Agnieszka',
    surname: 'Wojtyła',
    isWorking: false,
  },
  {
    pin: 101,
    name: 'Agnieszka',
    surname: 'Wojtyła',
    isWorking: false,
  },
  {
    pin: 101,
    name: 'Agnieszka',
    surname: 'Wojtyła',
    isWorking: false,
  },
  {
    pin: 101,
    name: 'Agnieszka',
    surname: 'Wojtyła',
    isWorking: false,
  },
  {
    pin: 101,
    name: 'Agnieszka',
    surname: 'Wojtyła',
    isWorking: false,
  },
  {
    pin: 101,
    name: 'Agnieszka',
    surname: 'Wojtyła',
    isWorking: false,
  },
  {
    pin: 102,
    name: 'Oleksandr',
    surname: 'Lysakov',
    isWorking: true,
  },
  {
    pin: 101,
    name: 'Agnieszka',
    surname: 'Wojtyła',
    isWorking: false,
  },
  {
    pin: 101,
    name: 'Agnieszka',
    surname: 'Wojtyła',
    isWorking: false,
  },
  {
    pin: 101,
    name: 'Agnieszka',
    surname: 'Wojtyła',
    isWorking: false,
  },
  {
    pin: 101,
    name: 'Agnieszka',
    surname: 'Wojtyła',
    isWorking: false,
  },
  {
    pin: 101,
    name: 'Agnieszka',
    surname: 'Wojtyła',
    isWorking: false,
  },
  {
    pin: 101,
    name: 'Agnieszka',
    surname: 'Wojtyła',
    isWorking: false,
  },
  {
    pin: 101,
    name: 'Agnieszka',
    surname: 'Wojtyła',
    isWorking: false,
  },
  {
    pin: 101,
    name: 'Agnieszka',
    surname: 'Wojtyła',
    isWorking: false,
  },
  {
    pin: 101,
    name: 'Agnieszka',
    surname: 'Wojtyła',
    isWorking: false,
  },
  {
    pin: 101,
    name: 'Agnieszka',
    surname: 'Wojtyła',
    isWorking: false,
  },
  {
    pin: 101,
    name: 'Agnieszka',
    surname: 'Wojtyła',
    isWorking: false,
  },
];
